# Exclude glob
# The paths are relative to obsidian_folder_path_str
# - Start with slash to target specific folder: /subfolder
# - Target any folder with name "subfolder": subfolder
# Glob patterns supported for copy_vault_to_tempdir_method: shutil, shutil_walk, and for rsync for as far as rsync supports it natively
#   When turning off copy_vault_to_tempdir, glob patterns are fully supported.
# Rules are case sensitive if your filesystem is.
exclude_glob:
  - "/.obsidian"
  - "/.trash"
  - "/.DS_Store"
  - "/.git"
  - "/excalidraw"
  - "/books"
  - "/datasets"
  - "prv_*"
